name: Build & Relase LaTeX document

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -8bit"
          pre_compile: |
            wget -q -O firacode.zip "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
            unzip -q firacode.zip -d firacode
            for i in woff2 variable_ttf ttf; do cp -r firacode/$i /usr/share/fonts/$i; done
            fc-cache -f
          root_file: |
            lecture.tex
            slice.tex
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ github.token }}
          file: "*.pdf"
          tag: ${{ github.ref }}
          file_glob: true
      - uses: actions/upload-artifact@v2
        with:
          name: slice & lecture
          path: |
            *.pdf
