name: Build & Relase LaTeX document

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: release tag name
        required: false
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -8bit"
          pre_compile: |
            wget -q -O firacode.zip "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
            unzip -q firacode.zip -d firacode
            cp -r firacode /usr/share/fonts
            fc-cache
          root_file: |
            lecture.tex
            slice.tex
      - name: create tag
        id: create_tag
        run: |
          tag_name=$(TZ="Africa/Abidjan" date +"v%Y%m%d-%H%M")
          if [[ -n "${{github.event.inputs.tag_name}}" ]]; then tag_name=${{github.event.inputs.tag_name}}; fi
          git tag $tag_name
          git push --tags
          echo "::set-output name=tag_name::$tag_name"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lecture.pdf
            slice.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: slice & lecture
          path: |
            ./lecture.pdf
            ./slice.pdf
